javac -encoding UTF-8 -d . src/mua/operationMap/*.java
javac -encoding UTF-8 -d . src/datatype/dataObject/*.java src/mua/variable/*.java
javac -encoding UTF-8 -d . src/mua/environment/*.java
javac -encoding UTF-8 -d . src/operation/add/*.java
javac -encoding UTF-8 -d . src/operation/and/*.java
javac -encoding UTF-8 -d . src/operation/butfirst/*.java
javac -encoding UTF-8 -d . src/operation/butlast/*.java
javac -encoding UTF-8 -d . src/operation/div/*.java
javac -encoding UTF-8 -d . src/operation/eq/*.java
javac -encoding UTF-8 -d . src/operation/erall/*.java
javac -encoding UTF-8 -d . src/operation/erase/*.java
javac -encoding UTF-8 -d . src/operation/eraseFunc/*.java
javac -encoding UTF-8 -d . src/operation/export/*.java
javac -encoding UTF-8 -d . src/operation/first/*.java
javac -encoding UTF-8 -d . src/operation/gt/*.java
javac -encoding UTF-8 -d . src/operation/intOperation/*.java
javac -encoding UTF-8 -d . src/operation/isbool/*.java
javac -encoding UTF-8 -d . src/operation/isempty/*.java
javac -encoding UTF-8 -d . src/operation/islist/*.java
javac -encoding UTF-8 -d . src/operation/isname/*.java
javac -encoding UTF-8 -d . src/operation/isnumber/*.java
javac -encoding UTF-8 -d . src/operation/isword/*.java
javac -encoding UTF-8 -d . src/operation/join/*.java
javac -encoding UTF-8 -d . src/operation/last/*.java
javac -encoding UTF-8 -d . src/operation/list/*.java
javac -encoding UTF-8 -d . src/operation/lt/*.java
javac -encoding UTF-8 -d . src/operation/make/*.java
javac -encoding UTF-8 -d . src/operation/mod/*.java
javac -encoding UTF-8 -d . src/operation/mul/*.java
javac -encoding UTF-8 -d . src/operation/not/*.java
javac -encoding UTF-8 -d . src/operation/or/*.java
javac -encoding UTF-8 -d . src/operation/print/*.java
javac -encoding UTF-8 -d . src/operation/random/*.java
javac -encoding UTF-8 -d . src/operation/read/*.java
javac -encoding UTF-8 -d . src/operation/readlist/*.java
javac -encoding UTF-8 -d . src/operation/save/*.java
javac -encoding UTF-8 -d . src/operation/sentence/*.java
javac -encoding UTF-8 -d . src/operation/sub/*.java
javac -encoding UTF-8 -d . src/operation/sqrt/*.java
javac -encoding UTF-8 -d . src/operation/thing/*.java
javac -encoding UTF-8 -d . src/operation/word/*.java
javac -encoding UTF-8 -d . src/operation/run/*.java src/operation/ifOperation/*.java src/operation/load/*.java
javac -encoding UTF-8 -d . src/mua/Main.java
